"""A股市场情绪指标算法（设计见 docs/SENTIMENT_ALGORITHM.md）。

分层约定：算法层只输出中性码值（`codes`），中文文案集中在 `labels`。
本包为纯计算：无 IO、无网络、无随机数。
"""

from __future__ import annotations

from . import codes, labels
from .config import (
    ComponentSpec,
    ScaleSpec,
    SentimentConfig,
    SentimentQuality,
    SentimentThresholds,
    SentimentWindows,
    derive_min_periods,
    resolve_method,
    resolve_min_periods,
    validate_config,
)
from .features import (
    BlendResult,
    ComponentMeta,
    FeatureBundle,
    ScaleResult,
    blend_scales,
    compute_base,
    compute_features,
    ema_features,
    midrank_percentile,
    rank_percentile,
    ratio_features,
    return_series,
    rolling_percentile,
    volume_ratio,
)
from .inputs import (
    AvailabilityReport,
    ColumnStatus,
    NormalizedInput,
    normalize_frame,
    profile_columns,
)
from .pipeline import (
    DEFAULT_OUTPUT_COLUMNS,
    REQUIRED_COLUMNS,
    SUPPORTED_COLUMNS,
    SentimentResult,
    analyze,
    compute_sentiment,
    output_columns,
    sentiment_snapshot,
)
from .registry import (
    DEFAULT_COMPONENTS,
    PROFILE_FAST,
    PROFILE_FAST_MIXED,
    PROFILE_MULTISCALE_SUGGESTED,
    WINDOW_PRESETS,
    config_for_profile,
    config_for_window,
    default_config,
    resolve_window,
    with_percentile_window,
)
from .scoring import (
    IndexResult,
    MacdVolumeResult,
    PanicResult,
    ReversalResult,
    ScoreBundle,
    classify_state,
    compose_index,
    index_band,
    macd_volume_metrics,
    panic_metrics,
    reversal_metrics,
    score_all,
)

__all__ = [
    'DEFAULT_COMPONENTS',
    'PROFILE_FAST',
    'PROFILE_FAST_MIXED',
    'PROFILE_MULTISCALE_SUGGESTED',
    'WINDOW_PRESETS',
    'AvailabilityReport',
    'BlendResult',
    'ColumnStatus',
    'ComponentMeta',
    'ComponentSpec',
    'DEFAULT_OUTPUT_COLUMNS',
    'FeatureBundle',
    'IndexResult',
    'MacdVolumeResult',
    'NormalizedInput',
    'PanicResult',
    'REQUIRED_COLUMNS',
    'ReversalResult',
    'ScoreBundle',
    'SentimentResult',
    'SUPPORTED_COLUMNS',
    'ScaleResult',
    'ScaleSpec',
    'SentimentConfig',
    'SentimentQuality',
    'SentimentThresholds',
    'SentimentWindows',
    'analyze',
    'blend_scales',
    'classify_state',
    'codes',
    'compute_base',
    'compute_features',
    'compute_sentiment',
    'compose_index',
    'config_for_profile',
    'config_for_window',
    'default_config',
    'derive_min_periods',
    'ema_features',
    'index_band',
    'labels',
    'macd_volume_metrics',
    'midrank_percentile',
    'normalize_frame',
    'output_columns',
    'panic_metrics',
    'profile_columns',
    'rank_percentile',
    'ratio_features',
    'resolve_method',
    'resolve_min_periods',
    'resolve_window',
    'reversal_metrics',
    'return_series',
    'rolling_percentile',
    'score_all',
    'sentiment_snapshot',
    'validate_config',
    'volume_ratio',
    'with_percentile_window',
]
